project:
  type: book
  output-dir: docs
book:
  title: "Políticas macro y micro prudenciales en la región"
  favicon: Luis.png
  language: custom.yml
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 01-conceptos.qmd
    - 02-CR.qmd
    - 03-SV.qmd
format:
  html:
    theme: journal
    code-fold: true
    include-after-body: graph_fold.html
  pdf:
    documentclass: scrreport